name          'nextrevision-flowtools'
version       '0.0.1'
source        'UNKNOWN'
author        'nextrevision'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib'
