name          'nextrevision-flowtools'
version '0.0.3'
source        'git://github.com/nextrevision/puppet-flowtools.git'
author        'nextrevision'
license       'Apache License, Version 2.0'
summary       'Module to install flow-tools and manage flow-capture'
description   'Used to install flow-tools and add flow-capture instances for devices'
project_page  'http://github.com/nextrevision/puppet-flowtools'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/concat'
